# Generated by Django 3.2.8 on 2021-10-23 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negotiate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='negotiation',
            name='request',
        ),
        migrations.RemoveField(
            model_name='request',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='request',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='id',
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='wallet_address',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Negotiation',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='work',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiate.seller'),
        ),
    ]
