# Generated by Django 3.2.8 on 2021-10-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiate', '0003_rename_wallet_address_work_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
